language: ruby
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - CODECLIMATE_REPO_TOKEN=0e53f23e1ed03ab327e184b7eaa07d9359bc6ce9bd6da8b5ea6bbe9b02c89f5f bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.4
